//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfControlLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfControlLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;messages&gt;
        ///	&lt;message&gt;
        ///		&lt;_type&gt;position_report&lt;/_type&gt;
        ///		&lt;_action&gt;update&lt;/_action&gt;
        ///		&lt;_id&gt;102991b1-ad06-412a-9e46-1d6464a4ba64&lt;/_id&gt;
        ///		&lt;_control_points&gt;-226750.39376,6680971.38044;-226585.9422,6680967.75384;-226425.36901,6680941.12366;-226273.55313,6680892.29906;-226135.1074,6680822.76355;-226014.23842,6680734.62992;-225914.61875,6680630.57608;-225839.27527,6680513.76364;-225790.49725,6680387.74189;-225769.7668,6680256.33995;-225777.71379,6680123.55039;-2258 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mil2525DMessages {
            get {
                return ResourceManager.GetString("Mil2525DMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot;?&gt;
        ///&lt;messages&gt;
        ///	&lt;message&gt;
        ///		&lt;_type&gt;position_report&lt;/_type&gt;
        ///		&lt;_action&gt;update&lt;/_action&gt;
        ///		&lt;_id&gt;102991b1-ad06-412a-9e46-1d6464a4ba64&lt;/_id&gt;
        ///		&lt;_control_points&gt;-226750.39376,6680971.38044;-226585.9422,6680967.75384;-226425.36901,6680941.12366;-226273.55313,6680892.29906;-226135.1074,6680822.76355;-226014.23842,6680734.62992;-225914.61875,6680630.57608;-225839.27527,6680513.76364;-225790.49725,6680387.74189;-225769.7668,6680256.33995;-225777.71379,6680123.55039;-2258 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mil2525DUnitMessages {
            get {
                return ResourceManager.GetString("Mil2525DUnitMessages", resourceCulture);
            }
        }
    }
}
